import enum


class Title(enum.Enum):
    SUBMISSION = 'PREDAN {} RAD, ULOGA: {}'
    STUDENT_TO_MENTOR_SUBMISSION = 'PREDALI STE {} RAD MENTORU'
    STUDENT_TO_PRESIDENT_SUBMISSION = 'PREDALI STE {} RAD PREDSJEDNIKU POVJERENSTVA'

    VERIFICATION = 'IZVRŠENA PROVJERA IZVORNOSTI'
    STATUS_CHANGE = 'PROMJENA STATUSA RADA'

    ADDED_TO_COMITEE = 'DODANI STE KAO ČLAN POVJERENSTVA DIPLOMSKOG RADA'
    ADDED_COMITEE = 'DODANI ČLANOVI POVJERENSTVA ZA DIPLOMSKI RAD'
    STUDENT_ADDED_COMITEE = 'DODANI ČLANOVI POVJERENSTVA ZA DIPLOMSKI RAD'

    BACHELOR_GRADE = 'UNESENA KONAČNA OCJENA ZAVRŠNOG RADA'
    MASTER_GRADE = 'UNESENA KONAČNA OCJENA DIPLOMSKOG RADA'
    COMITEE_MEMBER_ADDED_GRADE = 'UNESENE OCJENA RADA I OCJENA OBRANE'

    CHANGED_DOCUMENT = 'PROMJENA DOKUMENTA RADA'
